### ISSUE TITLE
Minor errors and changes for FAQ in FODL Gitbook

### ISSUE THREAD

**Issue by StackingEUR** [1bx0/fodl-gitbook#1]
- [x] Make changes to ''What is the tax wallet''

- What is the tax wallet? (Current version)
The tax wallet is where the FODL platform collects the revenue from the various positions opened on the platform. The DAO can determine the distribution mechanism for the tax wallet (i.e., token buyback, etc.) back to $FODL token holders [add link to the tax wallet?] What are the tokenomics of FODL? See here: https://fodl-1.gitbook.io/fodl-1/faq/tokenomics Has the platform been audited? Yes, the protocol has been audited by Quantstamp: https://certificate.quantstamp.com/full/fodl

Changes:

- Remove [Add link to tax wallet?]
- Make ''What are the tokenomics of FODL?'' and ''Has the platform been audited?'' separate questions and remove from the answer.

- [x] Delete ''How do I open a correlated position?'' question + answer

- [x] Change answer of ''How do I open a long position?'' to ''By going long, a trader opens a position with the expectation that the underlying borrowed (short) asset will drop in value against the supplied (long) asset in the future. Read here to see how to open a long position: https://fodl-1.gitbook.io/fodl-1/using-fodl/opening-a-long-position''

- [x] Change answer to ''How do I open a short position?'' to ''By going short, a trader opens a position with the expectation that the underlying borrowed (Short) asset will drop in value against the supplied (Long) asset in the future. Read here to see how to open a short position: https://fodl-1.gitbook.io/fodl-1/using-fodl/opening-a-short-position''

**Comment by crypto-perry** [comment]
Closed in commit: https://github.com/1bx0/fodl-gitbook/commit/2dc84973095f9f4e937bb3b1b0cbba20008ea59d
